import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// TODO: O componente Toaster precisa ser instalado via shadcn-ui.
// A instalação está falhando no momento. Depois de instalar, descomente as linhas abaixo.
// import { Toaster } from "@/components/ui/toaster"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* <Toaster /> */}
      </body>
    </html>
  );
}
